import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Compra recursiva",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-linear-to-br from-blue-500 to-purple-600 min-h-screen">
        <h1 className="text-4xl font-bold mb-8 text-center text-white mt-5">
          Mi Compra recursiva
        </h1>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
